services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: template
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d template"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "${POSTGRES_PORT:-55432}:5432"
    volumes:
      - template-postgres-data:/var/lib/postgresql

volumes:
  template-postgres-data:
