import { readFileSync, writeFileSync } from "node:fs";
import { z } from "zod";

interface RuleRow {
  invariant: string;
  owner: string;
  scope: string;
  severity: string;
  source: string;
}

const configSchema = z.object({
  overrides: z
    .array(
      z.object({
        files: z.array(z.string()).optional(),
        rules: z.record(z.string(), z.union([z.string(), z.array(z.unknown())])),
      }),
    )
    .optional(),
  rules: z.record(z.string(), z.union([z.string(), z.array(z.unknown())])),
});
const columns = ["Invariant", "Owner", "Severity", "Scope", "Source"];
const dynamicRulePattern =
  /["'](?<rule>[^"']+)["']:\s*["'](?<configuredSeverity>error|warn|off)["']/gu;

function readBaseConfig(): z.infer<typeof configSchema> {
  return configSchema.parse(JSON.parse(readFileSync("oxlint.base.json", "utf8")));
}

function severity(ruleValue: string | readonly unknown[]): string {
  if (typeof ruleValue === "string") {
    return ruleValue;
  }
  const [severityValue] = ruleValue;
  if (typeof severityValue === "string") {
    return severityValue;
  }
  return "configured";
}

function addRowsForRules(
  rows: RuleRow[],
  rules: Readonly<Record<string, string | readonly unknown[]>>,
  owner: string,
  scope: string,
  source: string,
): void {
  for (const [rule, ruleValue] of Object.entries(rules)) {
    rows.push({
      invariant: rule,
      owner,
      scope,
      severity: severity(ruleValue),
      source,
    });
  }
}

function escapeMarkdown(cell: string): string {
  return cell.replaceAll("*", String.raw`\*`);
}

function formatRow(row: readonly string[], widths: readonly number[]): string {
  return `| ${row
    .map((cell, index) => cell.padEnd(widths[index] ?? cell.length))
    .join(" | ")} |`;
}

const baseConfig = readBaseConfig();
const rows: RuleRow[] = [];
addRowsForRules(
  rows,
  baseConfig.rules,
  "Oxlint",
  "apps, packages, devtools/scripts",
  "oxlint.base.json",
);
for (const override of baseConfig.overrides ?? []) {
  addRowsForRules(
    rows,
    override.rules,
    "Oxlint override",
    override.files?.join(", ") ?? "scoped override",
    "oxlint.base.json",
  );
}

const dynamicConfig = readFileSync("oxlint.config.ts", "utf8");
for (const match of dynamicConfig.matchAll(dynamicRulePattern)) {
  const configuredSeverity = match.groups?.configuredSeverity;
  const rule = match.groups?.rule;
  if (
    typeof configuredSeverity === "string" &&
    configuredSeverity.length > 0 &&
    typeof rule === "string" &&
    rule.length > 0
  ) {
    rows.push({
      invariant: rule,
      owner: "Oxlint dynamic config",
      scope: "apps, packages, devtools/scripts",
      severity: configuredSeverity,
      source: "oxlint.config.ts",
    });
  }
}
if (dynamicConfig.includes("ALL_REACT_DOCTOR_RULES")) {
  rows.push({
    invariant: "react-quality/*",
    owner: "React Doctor registry",
    scope: "all linted files; explicit overrides recorded above",
    severity: "warn (denied)",
    source: "oxlint.config.ts",
  });
}

const markdownRows = rows
  .toSorted((left, right) =>
    `${left.invariant}:${left.scope}`.localeCompare(
      `${right.invariant}:${right.scope}`,
    ),
  )
  .map((row) =>
    [row.invariant, row.owner, row.severity, row.scope, row.source].map((cell) =>
      escapeMarkdown(cell),
    ),
  );
const widths = columns.map((column, index) =>
  Math.max(column.length, ...markdownRows.map((row) => row[index]?.length ?? 0)),
);
const rowsForMarkdown = [
  formatRow(columns, widths),
  formatRow(
    widths.map((width) => "-".repeat(width)),
    widths,
  ),
  ...markdownRows.map((row) => formatRow(row, widths)),
];
const generated = `<!-- Generated by devtools/scripts/repository/generate-enforcement-manifest.ts. Do not edit directly. -->

# Enforcement Manifest

This file is generated from the base Oxlint configuration, scoped overrides,
and the dynamic rules registered by oxlint.config.ts. The complete repository
gate also includes TypeScript, Oxfmt, Knip, dependency-cruiser, Sherif, shadcn
lint, security workflows, and test evidence.

${rowsForMarkdown.join("\n")}
`;
const outputPath = "docs/ENFORCEMENT-MANIFEST.md";
if (process.argv.includes("--write")) {
  writeFileSync(outputPath, generated);
} else if (readFileSync(outputPath, "utf8") !== generated) {
  process.stderr.write(`${outputPath} is stale; run pnpm enforcement:manifest:write\n`);
  process.exitCode = 1;
}
