import { readFileSync, writeFileSync } from "node:fs";

interface RuleRow {
  invariant: string;
  owner: string;
  severity: string;
  scope: string;
  source: string;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function severity(value: unknown): string {
  if (typeof value === "string") return value;
  if (Array.isArray(value) && typeof value[0] === "string") return value[0];
  return "configured";
}

const baseConfigPath = "oxlint.base.json";
const baseValue: unknown = JSON.parse(readFileSync(baseConfigPath, "utf8"));
if (!isRecord(baseValue) || !isRecord(baseValue.rules)) {
  throw new TypeError(`${baseConfigPath} has no rules object`);
}

const rows: RuleRow[] = Object.entries(baseValue.rules).map(([rule, value]) => ({
  invariant: rule,
  owner: "Oxlint",
  severity: severity(value),
  scope: "apps, packages, scripts",
  source: baseConfigPath,
}));

if (Array.isArray(baseValue.overrides)) {
  for (const override of baseValue.overrides) {
    if (!isRecord(override) || !isRecord(override.rules)) continue;
    const files: string[] = [];
    if (Array.isArray(override.files)) {
      files.push(
        ...override.files.filter((file): file is string => typeof file === "string"),
      );
    }
    const scope = files.join(", ");
    for (const [rule, value] of Object.entries(override.rules)) {
      rows.push({
        invariant: rule,
        owner: "Oxlint override",
        severity: severity(value),
        scope: scope || "scoped override",
        source: baseConfigPath,
      });
    }
  }
}

const dynamicConfig = readFileSync("oxlint.config.ts", "utf8");
const dynamicRules =
  /["'](?<rule>[^"']+)["']:\s*["'](?<configuredSeverity>error|warn|off)["']/gu;
for (const match of dynamicConfig.matchAll(dynamicRules)) {
  const rule = match.groups?.rule;
  const configuredSeverity = match.groups?.configuredSeverity;
  if (rule === undefined || configuredSeverity === undefined) continue;
  rows.push({
    invariant: rule,
    owner: "Oxlint dynamic config",
    severity: configuredSeverity,
    scope: "apps, packages, scripts",
    source: "oxlint.config.ts",
  });
}

if (dynamicConfig.includes("ALL_REACT_DOCTOR_RULES")) {
  rows.push({
    invariant: "react-quality/*",
    owner: "React Doctor registry",
    severity: "warn (denied)",
    scope: "all linted files; explicit overrides recorded above",
    source: "oxlint.config.ts",
  });
}

const columns = ["Invariant", "Owner", "Severity", "Scope", "Source"];
const escapeMarkdown = (value: string): string => value.replaceAll("*", String.raw`\*`);
const data = rows
  .toSorted((left, right) =>
    `${left.invariant}:${left.scope}`.localeCompare(
      `${right.invariant}:${right.scope}`,
    ),
  )
  .map((row) =>
    [row.invariant, row.owner, row.severity, row.scope, row.source].map((cell) =>
      escapeMarkdown(cell),
    ),
  );
const widths = columns.map((column, index) =>
  Math.max(column.length, ...data.map((row) => row[index]?.length ?? 0)),
);
const formatRow = (row: string[]): string =>
  `| ${row
    .map((cell, index) => cell.padEnd(widths[index] ?? cell.length))
    .join(" | ")} |`;
const rowsForMarkdown = [
  formatRow(columns),
  formatRow(widths.map((width) => "-".repeat(width))),
  ...data.map((row) => formatRow(row)),
];
const generated = `<!-- Generated by scripts/generate-enforcement-manifest.ts. Do not edit directly. -->

# Enforcement Manifest

This file is generated from the base Oxlint configuration, scoped overrides,
and the dynamic rules registered by oxlint.config.ts. The complete repository
gate also includes TypeScript, Oxfmt, Knip, dependency-cruiser, Sherif, shadcn
lint, security workflows, and test evidence.

${rowsForMarkdown.join("\n")}
`;

const outputPath = "docs/ENFORCEMENT-MANIFEST.md";
if (process.argv.includes("--write")) {
  writeFileSync(outputPath, generated);
} else if (readFileSync(outputPath, "utf8") !== generated) {
  console.error(`${outputPath} is stale; run pnpm enforcement:manifest:write`);
  process.exitCode = 1;
}
