import { readFileSync, writeFileSync } from "node:fs";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const config: unknown = JSON.parse(readFileSync(".oxlintrc.json", "utf8"));
if (!isRecord(config) || !isRecord(config.rules))
  throw new TypeError(".oxlintrc.json has no rules object");

const rules = Object.keys(config.rules).toSorted();
const columns = ["Invariant", "Owner", "Scope"];
const data = rules.map((rule) => [rule, "Oxlint", "apps, packages, scripts"]);
const widths = columns.map((column, index) =>
  Math.max(column.length, ...data.map((row) => row[index]?.length ?? 0)),
);
const formatRow = (row: string[]): string =>
  `| ${row.map((cell, index) => cell.padEnd(widths[index] ?? cell.length)).join(" | ")} |`;
const rows = [
  formatRow(columns),
  formatRow(widths.map((width) => "-".repeat(width))),
  ...data.map((row) => formatRow(row)),
];
const generated = `<!-- Generated by scripts/generate-enforcement-manifest.ts. Do not edit directly. -->

# Enforcement Manifest

This file is generated from the executable Oxlint configuration. The complete
repository gate also includes TypeScript, Oxfmt, Knip, dependency-cruiser,
Sherif, shadcn lint, React Doctor, security workflows, and test evidence.

${rows.join("\n")}
`;

const outputPath = "docs/ENFORCEMENT-MANIFEST.md";
if (process.argv.includes("--write")) {
  writeFileSync(outputPath, generated);
} else if (readFileSync(outputPath, "utf8") !== generated) {
  console.error(`${outputPath} is stale; run pnpm enforcement:manifest:write`);
  process.exitCode = 1;
}
